//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkBetter.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvnDataEntities : DbContext
    {
        public AvnDataEntities()
            : base("name=AvnDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiPhiDuAn> ChiPhiDuAns { get; set; }
        public virtual DbSet<DanhMucDuAn> DanhMucDuAns { get; set; }
        public virtual DbSet<DanhMucHopDong> DanhMucHopDongs { get; set; }
        public virtual DbSet<DuAn> DuAns { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LienHeKhachHang> LienHeKhachHangs { get; set; }
        public virtual DbSet<LienKetList> LienKetLists { get; set; }
        public virtual DbSet<LienKet> LienKets { get; set; }
        public virtual DbSet<MocThoiGian> MocThoiGians { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhanXet> NhanXets { get; set; }
        public virtual DbSet<NhomKhachHang> NhomKhachHangs { get; set; }
        public virtual DbSet<PhuLucHopDong> PhuLucHopDongs { get; set; }
        public virtual DbSet<Reminder> Reminders { get; set; }
        public virtual DbSet<RuiRo> RuiRoes { get; set; }
        public virtual DbSet<SoGhiChepList> SoGhiChepLists { get; set; }
        public virtual DbSet<SoGhiChep> SoGhiCheps { get; set; }
        public virtual DbSet<TaskList> TaskLists { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<ThanhLyHopDong> ThanhLyHopDongs { get; set; }
        public virtual DbSet<ThanhToanHoaDon> ThanhToanHoaDons { get; set; }
    }
}
