//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkBetter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.ThanhToanHoaDons = new HashSet<ThanhToanHoaDon>();
        }
    
        public int Id { get; set; }
        public int DuAnId { get; set; }
        public string SoHoaDon { get; set; }
        public Nullable<System.DateTime> NgayHoaDon { get; set; }
        public string SoTienChuaThue { get; set; }
        public string ThueGTGT { get; set; }
        public int NguoiLapHoaDon { get; set; }
        public System.DateTime ThoiGianLapHoaDon { get; set; }
        public string TinhTrangHoaDon { get; set; }
    
        public virtual DuAn DuAn { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToanHoaDon> ThanhToanHoaDons { get; set; }
    }
}
