//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkBetter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.HopDongs = new HashSet<HopDong>();
            this.LienHeKhachHangs = new HashSet<LienHeKhachHang>();
        }
    
        public int Id { get; set; }
        public string MaKhachHang { get; set; }
        public string TenKhachHang { get; set; }
        public string GhiChu { get; set; }
        public string DiaChi { get; set; }
        public int NhomKhachHangId { get; set; }
        public string Email { get; set; }
        public string DienThoai { get; set; }
        public string Website { get; set; }
        public int NguoiThem { get; set; }
        public System.DateTime ThoiGianThem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong> HopDongs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LienHeKhachHang> LienHeKhachHangs { get; set; }
        public virtual NhomKhachHang NhomKhachHang { get; set; }
    }
}
