//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkBetter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienKetList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LienKetList()
        {
            this.LienKets = new HashSet<LienKet>();
        }
    
        public int Id { get; set; }
        public string TenNhomLienKet { get; set; }
        public string GhiChu { get; set; }
        public int NguoiTao { get; set; }
        public System.DateTime ThoiGianTao { get; set; }
        public int DuAnId { get; set; }
    
        public virtual DuAn DuAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LienKet> LienKets { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
