//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkBetter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int Id { get; set; }
        public string NhanVienList { get; set; }
        public int NguoiTao { get; set; }
        public System.DateTime ThoiGianTao { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime ThoiGianNhacNho { get; set; }
        public int DuAnId { get; set; }
    
        public virtual DuAn DuAn { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
