//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkBetter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuiRo
    {
        public int Id { get; set; }
        public string NguonRuiRo { get; set; }
        public string MoTa { get; set; }
        public string KhaNangXayRa { get; set; }
        public string MucDoAnhHuong { get; set; }
        public string TinhTrang { get; set; }
        public int NguoiXacDinh { get; set; }
        public System.DateTime ThoiGianXacDinh { get; set; }
        public string GhiChu { get; set; }
        public int DuAnId { get; set; }
    
        public virtual DuAn DuAn { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
