//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkBetter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoGhiChep
    {
        public int Id { get; set; }
        public string Ten { get; set; }
        public string MoTa { get; set; }
        public int SoGhiChepListId { get; set; }
        public System.DateTime NgayGioTao { get; set; }
        public int NguoiTao { get; set; }
        public byte[] NoiDung { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual SoGhiChepList SoGhiChepList { get; set; }
    }
}
