//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkBetter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public int TaskListId { get; set; }
        public int NguoiTaoTask { get; set; }
        public System.DateTime ThoiGianTaoTask { get; set; }
        public string NoiDung { get; set; }
        public string ChiTiet { get; set; }
        public byte MucDoUuTien { get; set; }
        public byte TienDo { get; set; }
        public Nullable<long> ThoiGianUocTinhHoanThanh { get; set; }
        public string Tag { get; set; }
        public string NhacNho { get; set; }
        public string ThongBao { get; set; }
        public System.DateTime ThoiGianDenHan { get; set; }
        public string NhanVienList { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual TaskList TaskList { get; set; }
    }
}
