//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkBetter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToanHoaDon
    {
        public int Id { get; set; }
        public int NguoiGhiSo { get; set; }
        public System.DateTime ThoiGianGhiSo { get; set; }
        public string SoTienThanhToan { get; set; }
        public int HoaDonId { get; set; }
        public int DuAnId { get; set; }
    
        public virtual DuAn DuAn { get; set; }
        public virtual HoaDon HoaDon { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
